#!/usr/bin/env python3
#
# (c) Stephen Bates, 2020
#
# wemo-exporter
# -------------
#
# https://github.com/sbates130272/wemo-exporter
#
# requires pywemo (pip install pywemo)
# requires https://github.com/prometheus/client_python (pip install prometheus_client)

from prometheus_client import start_http_server, Gauge
import pywemo
import time

IP_ADDRESS="10.0.0.167"

WEMO_POWER = Gauge('wemo_power', 'Wemo Insight Power (W)')

if __name__=="__main__":

    try:
        devices = pywemo.discover_devices()
        print(devices)
        device = devices[0]
    except:
        address = IP_ADDRESS
        port = pywemo.ouimeaux_device.probe_wemo(address)
        url = 'http://%s:%i/setup.xml' % (address, port)
        device = pywemo.discovery.device_from_description(url, None)

    start_http_server(9632)

    while True:

        device.update_insight_params()
        current_power_mw = float(device.current_power)

        print(current_power_mw)
        WEMO_POWER.set(current_power_mw/1000.0)
        time.sleep(10)
